Добавил activity в AndroidManifest.xml для перехвата ссылки для подтв…
ToosaFinder/toosa-finder-android pull request #4
Opened 2020-10-04 13:34 UTC by S-Pavlov1

…ерждения email пользователя. Создал emailVerificationActivity для обработки ссылки и получения Uuid

#3993 @ 4 часа

2020-10-04 15:03 UTC, paulpaulych requested changes

2020-10-04 15:03 UTC, palsergech commented on app/src/main/AndroidManifest.xml
> +            android:name="com.toosafinder.emailVerification.emailVerificationActivity"
Во всей системе это называется emailConfirmation
Поменяй для однородности пж

2020-10-04 15:03 UTC, palsergech commented on app/src/main/AndroidManifest.xml
> +                    android:pathPrefix="/user/confirmEmail" />
есть ли возможность взять эти значения из файлика с пропертями, чтобы каждый раз в манифест не лезть?

2020-10-04 15:03 UTC, palsergech commented on app/src/main/java/com/toosafinder/emailVerification/emailVerificationActivity.kt
> +        val data: Uri? = intent?.data
тут полюбому должен быть урл. Если его по каким-то причинам нет, то должно исключение лететь как я понимаю, которое в каком-нибудь глобальном обработчике обработается

2020-10-04 15:03 UTC, palsergech commented on app/src/main/java/com/toosafinder/emailVerification/emailVerificationActivity.kt
> +class emailVerificationActivity : AppCompatActivity() {
С большой буквы, ну

2020-10-04 15:03 UTC, palsergech commented on app/src/main/java/com/toosafinder/emailVerification/emailVerificationActivity.kt
> +
Пусть это будет не id, а emailToken
Его надо передать на следующий слой чтобы можно было на сервер отправить

2020-10-04 15:03 UTC, palsergech commented on app/src/main/java/com/toosafinder/emailVerification/emailVerificationActivity.kt
> +    private fun parceData(data : Uri?) : String {
Давай чтобы без вопросиков. Если УРЛа нет, то этот метод тут не причем

2020-10-04 15:03 UTC, palsergech commented on app/src/main/java/com/toosafinder/emailVerification/emailVerificationActivity.kt
> +        //вопрос : что делать в случае, если пришел мусор в ссылке в последнем сегменте
Строчку не надо возвращать точно. Давай на Sealed классах. Там в коде должны быть примеры как это делается.
что-то типа :
 
sealed class UrlParsingRes{
   data class Success(val lastSegment: String): UrlParsingRes()
  object Error: UrlParsingRes()
} 

и вынести этот метод отдельно, чтобы можно было для сброса пароля тоже использовать

А еще лучше на следующий слой отправить весь УРЛ. И не делать никакого парсинга в активити

2020-10-04 15:03 UTC, palsergech commented on app/src/main/java/com/toosafinder/emailVerification/emailVerificationActivity.kt
> +        return data.lastPathSegment!!
на форматирование обрати внимание. Идея делает это по Ctrl+Alt+L

2020-10-07 16:04 UTC, paulpaulych requested changes

2020-10-07 16:04 UTC, palsergech commented on app/src/main/java/com/toosafinder/emailConfirmation/EmailConfirmationActivity.kt
> +        val data: Uri = intent?.data!!
!! Использовать крайне не рекомендуется. Надо обработать

2020-11-21 17:23 UTC, GolikovMaxim approved these changes
Good job!

2020-11-22 10:48 UTC, GolikovMaxim commented on app/src/main/java/com/toosafinder/emailConfirmation/EmailConfirmationActivity.kt
> +        val data: Uri = intent?.data!!
Сережа это исправил

2020-11-22 10:49 UTC, GolikovMaxim approved these changes
Молодец!

2020-11-22 11:25 UTC, GolikovMaxim approved these changes

2020-11-22 11:26 UTC, merged